//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeRateData", Namespace="http://schemas.datacontract.org/2004/07/MyWcfService")]
    [System.SerializableAttribute()]
    public partial class ExchangeRateData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double BuyRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double SellRateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double BuyRate {
            get {
                return this.BuyRateField;
            }
            set {
                if ((this.BuyRateField.Equals(value) != true)) {
                    this.BuyRateField = value;
                    this.RaisePropertyChanged("BuyRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SellRate {
            get {
                return this.SellRateField;
            }
            set {
                if ((this.SellRateField.Equals(value) != true)) {
                    this.SellRateField = value;
                    this.RaisePropertyChanged("SellRate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WalletItem", Namespace="http://schemas.datacontract.org/2004/07/MyWcfService")]
    [System.SerializableAttribute()]
    public partial class WalletItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuySellRates", ReplyAction="http://tempuri.org/IService1/GetBuySellRatesResponse")]
        WpfApp1.ServiceReference1.ExchangeRateData GetBuySellRates(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBuySellRates", ReplyAction="http://tempuri.org/IService1/GetBuySellRatesResponse")]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.ExchangeRateData> GetBuySellRatesAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        bool RegisterUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        int LoginUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LoginUser", ReplyAction="http://tempuri.org/IService1/LoginUserResponse")]
        System.Threading.Tasks.Task<int> LoginUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        decimal GetBalance(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBalance", ReplyAction="http://tempuri.org/IService1/GetBalanceResponse")]
        System.Threading.Tasks.Task<decimal> GetBalanceAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFunds", ReplyAction="http://tempuri.org/IService1/AddFundsResponse")]
        bool AddFunds(int userId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddFunds", ReplyAction="http://tempuri.org/IService1/AddFundsResponse")]
        System.Threading.Tasks.Task<bool> AddFundsAsync(int userId, decimal amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        bool BuyCurrency(int userId, string currencyCode, decimal amountToBuy, decimal currentRate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuyCurrency", ReplyAction="http://tempuri.org/IService1/BuyCurrencyResponse")]
        System.Threading.Tasks.Task<bool> BuyCurrencyAsync(int userId, string currencyCode, decimal amountToBuy, decimal currentRate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        bool SellCurrency(int userId, string currencyCode, decimal amountToSell, decimal currentRate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SellCurrency", ReplyAction="http://tempuri.org/IService1/SellCurrencyResponse")]
        System.Threading.Tasks.Task<bool> SellCurrencyAsync(int userId, string currencyCode, decimal amountToSell, decimal currentRate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserCurrencies", ReplyAction="http://tempuri.org/IService1/GetUserCurrenciesResponse")]
        WpfApp1.ServiceReference1.WalletItem[] GetUserCurrencies(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetUserCurrencies", ReplyAction="http://tempuri.org/IService1/GetUserCurrenciesResponse")]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.WalletItem[]> GetUserCurrenciesAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WpfApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WpfApp1.ServiceReference1.IService1>, WpfApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WpfApp1.ServiceReference1.ExchangeRateData GetBuySellRates(string currencyCode) {
            return base.Channel.GetBuySellRates(currencyCode);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.ServiceReference1.ExchangeRateData> GetBuySellRatesAsync(string currencyCode) {
            return base.Channel.GetBuySellRatesAsync(currencyCode);
        }
        
        public bool RegisterUser(string username, string password) {
            return base.Channel.RegisterUser(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string username, string password) {
            return base.Channel.RegisterUserAsync(username, password);
        }
        
        public int LoginUser(string username, string password) {
            return base.Channel.LoginUser(username, password);
        }
        
        public System.Threading.Tasks.Task<int> LoginUserAsync(string username, string password) {
            return base.Channel.LoginUserAsync(username, password);
        }
        
        public decimal GetBalance(int userId) {
            return base.Channel.GetBalance(userId);
        }
        
        public System.Threading.Tasks.Task<decimal> GetBalanceAsync(int userId) {
            return base.Channel.GetBalanceAsync(userId);
        }
        
        public bool AddFunds(int userId, decimal amount) {
            return base.Channel.AddFunds(userId, amount);
        }
        
        public System.Threading.Tasks.Task<bool> AddFundsAsync(int userId, decimal amount) {
            return base.Channel.AddFundsAsync(userId, amount);
        }
        
        public bool BuyCurrency(int userId, string currencyCode, decimal amountToBuy, decimal currentRate) {
            return base.Channel.BuyCurrency(userId, currencyCode, amountToBuy, currentRate);
        }
        
        public System.Threading.Tasks.Task<bool> BuyCurrencyAsync(int userId, string currencyCode, decimal amountToBuy, decimal currentRate) {
            return base.Channel.BuyCurrencyAsync(userId, currencyCode, amountToBuy, currentRate);
        }
        
        public bool SellCurrency(int userId, string currencyCode, decimal amountToSell, decimal currentRate) {
            return base.Channel.SellCurrency(userId, currencyCode, amountToSell, currentRate);
        }
        
        public System.Threading.Tasks.Task<bool> SellCurrencyAsync(int userId, string currencyCode, decimal amountToSell, decimal currentRate) {
            return base.Channel.SellCurrencyAsync(userId, currencyCode, amountToSell, currentRate);
        }
        
        public WpfApp1.ServiceReference1.WalletItem[] GetUserCurrencies(int userId) {
            return base.Channel.GetUserCurrencies(userId);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.ServiceReference1.WalletItem[]> GetUserCurrenciesAsync(int userId) {
            return base.Channel.GetUserCurrenciesAsync(userId);
        }
    }
}
